version: '3'

services:
  ionic-ui:
    build:
      context: ./src/frontend/dam
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    container_name: ionic-ui
    volumes:
      - ./src/frontend/dam:/src/frontend/dam
      - /src/frontend/dam/node_modules
    command: ionic serve --external

  mariadb-server:
    image: tobi312/rpi-mariadb:10.6-alpine
    hostname: mariadb-server
    environment:
      MARIADB_ROOT_PASSWORD: userpass
    container_name: mariadb-server
    volumes:
      - ./db/dumps:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    networks:
      - app-fullstack-net
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mariadb-server
      PMA_PORT: 3306
      MARIADB_ROOT_PASSWORD: userpass
    container_name: phpmyadmin
    networks:
      - app-fullstack-net
    depends_on:
      - mariadb-server
    ports:
      - "8001:80"

  node-backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: node-backend
    volumes:
      - ./src/backend:/home/node/app/src
      - ./src/frontend:/home/node/app/static
    networks:
      - app-fullstack-net
    depends_on:
      - mariadb-server
    ports:
      - "8000:3000"
    command: nodemon /home/node/app/src/index.js

networks:
  app-fullstack-net:
    driver: bridge
